# Generated by Django 3.2.9 on 2021-12-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='game_creator',
        ),
    ]
