# Generated by Django 3.2.9 on 2021-12-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='maker',
            field=models.CharField(default='game company name', max_length=50),
        ),
        migrations.AddField(
            model_name='games',
            name='number_of_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='games',
            name='skill_level',
            field=models.IntegerField(default=1),
        ),
    ]
