# Generated by Django 3.2.9 on 2021-12-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='attendees',
            field=models.ManyToManyField(related_name='MyEvents', to='levelupapi.Gamer'),
        ),
    ]
