# Generated by Django 3.2.9 on 2021-12-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_alter_events_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='levelupapi.games'),
        ),
    ]
