# Generated by Django 3.2.9 on 2022-01-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(default='Unnamed Event', max_length=50),
        ),
    ]
