# Generated by Django 3.2.9 on 2022-01-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0008_alter_events_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(default='No Description Given', max_length=50),
        ),
    ]
