# Generated by Django 3.2.9 on 2022-01-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0010_alter_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attendees',
            field=models.ManyToManyField(related_name='my_events', to='levelupapi.Gamer'),
        ),
    ]
