# Generated by Django 3.2.9 on 2022-01-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0011_alter_events_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attendees',
            field=models.ManyToManyField(related_name='attending', to='levelupapi.Gamer'),
        ),
    ]
